-- Reset and seed the notebook with the 10 chapters from Dennis's notes.
DELETE FROM public.stories;

INSERT INTO public.stories (slug, title, intro, body, sort_order) VALUES
('asparagus-season',
 'Asparagus Season',
 'Every spring, my best friend and I return to the same restaurant in Amsterdam for one very special dish: Dutch white asparagus.',
 'I grew up in the south of the Netherlands, where white asparagus is a true seasonal delicacy. Every spring we celebrate the season with a traditional Dutch meal, a good glass of wine, and a table by the canal. It''s one of those simple traditions I look forward to every year, because asparagus tastes best when nature says it''s time.',
 1),
('the-bike-exam',
 'The Bike Exam',
 'I recently got a photo from my nephew proudly holding his bike certificate after passing his cycling exam.',
 'Around the age of ten or eleven, every child in my country takes an official bike exam at school. The morning starts with written questions, followed by a cycling route through the neighborhood while teachers and parents watch at every crossing. At the end of the day, there''s a certificate waiting. Such a wonderfully Dutch tradition.',
 2),
('rhododendron-dream',
 'Rhododendron Dream',
 'In a national park about an hour from Amsterdam, there''s a museum with the second largest Van Gogh collection in the world, surrounded by forest and a beautiful sculpture garden.',
 'I was there with guests in spring when the rhododendrons were in full bloom. The garden became a maze of paths between deep pink and purple blossoms, buzzing with insects. It felt like stepping into another world, almost a fantasy landscape where nature, art and silence come together.',
 3),
('speculaas-cookie',
 'Speculaas Cookie',
 'Maybe the best cookie in the Netherlands. Speculaas is a spiced Dutch biscuit loved by every generation.',
 'I grew up loving speculaas, and I still stop for it whenever I pass a bakery near my neighborhood in Amsterdam. The smell of these cookies is instantly recognizable. Today you can buy them all year round, from simple biscuits to beautifully decorated tins that make wonderful gifts for children, and secretly, for adults too.',
 4),
('the-book-of-amsterdam',
 'The Book of Amsterdam',
 'Last week I gave a book about Amsterdam to one of my guests, a book I have given many times before to guests and new people in Amsterdam.',
 'Written by Dutch author Geert Mak, it feels like your history teacher brought the city itself to life. If you love history, you''ll know the feeling of getting lost in a really good book. It captures the history, culture and everyday life of Amsterdam in a very special way: Amsterdam, A Brief Life of the City.',
 5),
('nijntje-in-the-city',
 'Nijntje in the City',
 'I recently had children on my tour and always take them to the Nijntje store in Amsterdam. Nijntje, known internationally as Miffy, is the most famous Dutch children''s book character.',
 'When I was a child, Nijntje was already everywhere, today still loved by both children and adults. Nijntje has become a true cultural icon in the Netherlands. I love bringing guests to the shop because it''s simple, timeless, and full of childhood memories. A Nijntje gift is a wonderful present for newborns and young children.',
 6),
('park-escape',
 'Park Escape',
 'Whenever I want a quiet moment and let the world pass by, I often go to a park in Amsterdam North along the River IJ.',
 'The park is a tribute to the elm tree, the city tree of Amsterdam, giving the space a quiet, symbolic connection to the city. When I sit there, it feels like Amsterdam slows down. It''s a place for reading, sunshine, and watching boats on the River IJ, while the historic city center feels far away.',
 7),
('van-gogh-in-bricks',
 'Van Gogh in Bricks',
 'Because of my love for his work, I visit the museum between 10 and 20 times a year with guests, friends, or sometimes alone.',
 'Whenever I''m at the Van Gogh Museum, I often find myself in the shop looking at Lego sets inspired by Van Gogh paintings. One of the Lego sets is The Starry Night, with 2,316 pieces. I bought that set and loved building it. The most special detail is the Vincent van Gogh minifigure, which I added to my ever-growing collection.',
 8),
('ice-cream-patrol',
 'Ice Cream Patrol',
 'While cycling through one of my favorite neighborhoods on my way to get an ice cream, I witnessed one of those wonderfully Amsterdam moments.',
 'Two police officers on horseback stopped outside the ice cream shop just before I did. One jumped off while the other held both horses, then returned with two ice creams. After handing one over, they rode away together into a street glowing in the evening sun. Everyone smiled, especially the children. It was such a simple, joyful scene I''ll never forget.',
 9),
('bridge-jumpers',
 'Bridge Jumpers',
 'During hot summer days in Amsterdam, there is only one thing everybody wants to do: jump into the water.',
 'I often go swimming in the canals just a few minutes from my house. The banks are usually full of people enjoying the sunshine. But the best part is watching the local children lining up on a bridge, waiting for their turn to jump into the canal. Officially it''s not allowed, but on hot days it''s one of those little Amsterdam traditions that somehow still happens.',
 10);
